name: Hardlands
version: '${version}'
main: io.github.pepe3012.hardlands.Hardlands
api-version: '26.2'
load: POSTWORLD
authors:
  - Pepe3012
permissions:
  hardlands.admin:
    description: Access to Hardlands admin commands
    default: op
dependencies:
  server:
    Chunky:
      load: BEFORE
      required: true
      join-classpath: true
libraries:
  - com.google.code.gson:gson:2.14.0