name: Hardlands
version: '${version}'

main: com.hardlands.HardlandsPlugin
api-version: '26.2'
load: POSTWORLD

authors:
  - Pepe3012

permissions:
  hardlands.admin:
    description: Access to Hardlands admin commands
    default: op

dependencies:
  server:
    Chunky:
      load: BEFORE
      required: true
      join-classpath: true